### ISSUE TITLE
Error   File "app.py", line 47, in model_predict     ts = int(str(path)[index1:index2]) ValueError: invalid literal for int() with base 10: 'ds/sample'

### ISSUE THREAD

**Issue by robertavram-md** [ankur219/ECG-Arrhythmia-classification#2]
Hello,
Thank you for uploading and sharing this code.
I was wondering if you could double check if it is working for you.
I am using the sample.csv file provided in your GH repo.
I get this error : `  File "app.py", line 47, in model_predict
    ts = int(str(path)[index1:index2])
ValueError: invalid literal for int() with base 10: 'ds/sample'`

**Comment by juniorcoder34** [comment]
I have encountered the same error.

**Comment by jigar786** [comment]
Even same error i have encountered. Any solutuions Please.

**Comment by nikhil-elayath** [comment]
Same here. Any solutions?

**Comment by ankur219** [comment]
I have updated the repo. Let me know if its working.
